ivaldi/brimir

config/locales/ru.yml

one more fixes in russian translation

more fixes in russian translation

---

config/locales/pt-BR.yml

improving brazilian portuguese locale

---

README.md
script/post-mail

bash seems redundant here, use posix sh is enough and should be a bit faster and secure

Use sh instead of bash

---

config/locales/ru.yml

update ru locale

---

README.md

I just wanted to update the README. Thanks.

updating README for generating secret on mac

---

config/locales/tr.yml

Translated brimir to turkish language.

Turkish language translantion

---

app/views/tickets/_form.html.erb
app/views/tickets/_priority_dropdown.html.erb

Allow setting ticket priority from create form.

set ticket priority in create form.

---

app/views/tickets/_form.html.erb

Allow setting assignee in ticket creation form.

set ticket assignee in create form.

---

app/models/concerns/ticket_merge.rb
test/models/merged_ticket_test.rb

Fixing #268.
Discussion: See https://github.com/ivaldi/brimir/issues/268.

Merge tickets: 	Copy over notified users from younger tickets.

---

app/views/devise/sessions/new.html.erb

Only the E-mail field was getting localized currently, so this looks very strange when changing language.

Localize password field

---

CHANGELOG.md
Gemfile
Gemfile.lock
README.md
app/assets/javascripts/application.js
app/assets/stylesheets/_forms.scss
app/assets/stylesheets/application.scss
app/views/email_templates/_form.html.erb
app/views/replies/_form.html.erb
app/views/tickets/_form.html.erb
app/views/users/_form.html.erb
config/locales/en.yml
config/locales/nl.yml

This pull request should fix issue [#172](https://github.com/ivaldi/brimir/issues/172).
When pulling this request all instances of tinymce in the application will be changed to the more modern and less bloated Trix WYSIWYG editor.

Replaced tinymce with trix (WYSIWYG editor)

---

CHANGELOG.md
app/controllers/tickets_controller.rb
app/views/replies/_form.html.erb

This should fix an issue with with the signatures not appearing and notifications not being send to agents, due to logic error introduced in commit [0.7.1-34-gaf9bedf](https://github.com/ivaldi/brimir/blob/af9bedf7ae4f8abf6231290ee6d1e95cfa9f3a98/app/controllers/tickets_controller.rb#L209-L218)

Fix error with signature

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/components.js
app/assets/javascripts/components/rule_fields.es6.jsx
app/controllers/rules_controller.rb
app/views/rules/_form.html.erb
config/locales/en.yml
config/locales/nl.yml

This prevents lots of errors, for example non-existing statuses or typo's in user email addresses.

Add React component to manage rules

---

CHANGELOG.md
app/controllers/tickets_controller.rb
app/models/ticket.rb

This pull request should fix issue [#299](https://github.com/ivaldi/brimir/issues/299).

Fixed issue with tickets missing a message_id

---

CHANGELOG.md
app/assets/javascripts/application.js
app/helpers/application_helper.rb
app/views/tickets/_form.html.erb

This will add tab indexes on all fields of the form, which will help for a better UX.

Tab index for ticket form

---

app/controllers/tickets_controller.rb
config/locales/en.yml
config/locales/nl.yml

Just some refactoring, mainly syntax changes. Added some dutch translations as well.

Refactored tickets_controller, added some dutch translations

---

CHANGELOG.md
test/controllers/tickets_controller_test.rb

This PR should extend the current test suite with tests for the captcha, as this functionality is not being covered or very minimal at the time of writing this post.

Added tests for captcha

---

app/assets/javascripts/application.js

This should fix the javascript error cannot read propety tabIndex

Added fix tabindex property not found

---

app/views/email_templates/_form.html.erb
app/views/users/_form.html.erb

In commit 0ee0230 I fixed an issue with navigation not working due to tabindex being added for the trix editor by a javascript function,  it seems I forgot to add the tabindex to some pages which causes this issue to arise here aswell, this should fix the problem.

Extending fix first implemented in commit 0ee0230 (forgot some stuff)

---

CHANGELOG.md
app/controllers/tickets_controller.rb
db/migrate/20161214155109_add_default_ticket_creation_is_open_to_the_world_to_tenants.rb
db/schema.rb

This PR should fix issue [#327](https://github.com/ivaldi/brimir/issues/327).

Fixed issue with saved_with_label called upon a ticket

---

CHANGELOG.md
config/locales/en.yml
config/locales/nl.yml

Some translations were missing, added them.

Missing translations english dutch

---

app/assets/javascripts/application.js
app/views/users/_form.html.erb

This PR should make the schedule invisible for non agents and has the changes merged in from the [branch](https://github.com/ivaldi/brimir/tree/remove_class_to_fix_back_button) created by @basschoen.

No schedule for non agents

---

CHANGELOG.md
app/controllers/tickets_controller.rb
app/models/schedule.rb

I came across some unused code, this will clean it up

Cleanup unused code

---

CHANGELOG.md
app/views/tickets/index.html.erb

This PR fixes #335, not the nicest solution but for now it works.

Fix (for now) bomb not destroying all tickets inside trash

---

README.md
app/assets/javascripts/components/rule_fields.es6.jsx

This PR includes minor changes to the README.md and fixes a small issue with not being able to select an action in the rule form

Updated the readme and fix select issue in rule form

---

config/locales/fr-FR.yml

some translations were wrong/missing, added some

Corrected / added some translations

---

Gemfile
Gemfile.lock

fixes https://github.com/ivaldi/brimir/issues/305.
See also:
https://github.com/basecamp/trix/issues/340
https://github.com/maclover7/trix/issues/35

update trix editor to 0.10.1

---

app/views/replies/_reply.html.erb

If attachments exist for reply to a ticket, adds paperclip icon beside updated at time.
Fixes #349

Add attachment icon to reply in reply list for ticket

---

app/controllers/application_controller.rb
app/views/layouts/application.html.erb

As part of #364, I noticed there was some logic related to the initial "Joyride" component, so I've moved that into the controller.

Moved the Joyride logic out of the view

---

config/locales/de.yml

Fixed a typo and added a translation for :attach_note

Fix german translation

---

config/locales/pt-BR.yml

Hey guys,
It's just some typos fixes in pt-BR locale.

Fix some typos in pt-BR locale

---

README.md
app/controllers/concerns/users_strong_params.rb
app/controllers/tickets_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/views/replies/_notified_users.html.erb
app/views/tickets/_form.html.erb
app/views/users/_form.html.erb
app/views/users/index.html.erb
config/locales/en.yml
db/migrate/20171016140901_add_is_active_to_users.rb
db/schema.rb

add related checkbox in users page for searchinf.
refactored to display only active user.
updated english locale.
updated readme file.

add checkbox to disables user.

---

.travis.yml

Updating to the latest ruby versions, as well as adding ruby-head to keep an eye on the future.

update ruby versions in travis config

---

app/controllers/replies_controller.rb
app/controllers/tickets_controller.rb
app/views/replies/_notified_users.html.erb

This sets a couple instance vars that were missed on 2afd43f so that the travis build passes again.

set missing instance vars to fix travis

---

.travis.yml

Updated the Travis config to test against the latest ruby updates.

update rubies in travis config

---

app/models/reply.rb

Fix ticket split
