app/helpers/avatar_helper.rb

I've seen that you've updated the design. However the new avatar styles did not work when fetching the avatars from an api.
This is because the css class options has not been used when using the `AvatarHelper#user_avatar_from_api` method. Therefore, avatars have been not styled correctly when fetching avatars through an api.
This commit fixes this problem.
----
Before this commit:
After this commit:

fixing user avatars for new design when fetching the avatars from api.

---

app/assets/stylesheets/_foundation_and_overrides.scss
app/controllers/tickets_controller.rb
app/models/ticket.rb
app/views/tickets/index.html.erb
app/views/tickets/show.html.erb
config/locales/de.yml
config/locales/en.yml
config/routes.rb

This pull request adds a mechanism to quickly list all tickets created by a certain user. 
Also, adding some missing German translations.
Clicking on a user’s email address in `tickets#index` or `tickets#show`
leads to `tickets#index` where all tickets by that user are shown.
This view shows tickets in all states, i.e. also closed tickets, in
order to provide a quick way to look up all tickets by a certain user.
When in this filtered mode, a filter bar is shown in `tickets#index`.
Clicking on the filter entry removes the filter.

adding feature: filter by user

---

app/mailers/notification_mailer.rb
test/mailers/notification_mailer_test.rb

This is intended to prevent a situation where an
infinite loop of e-mails can be created by accidentaly
notifying our own e-mail when responding to a ticket.

Prevent outgoing e-mail to support address

---

app/assets/stylesheets/_topbar.scss
app/views/layouts/application.html.erb

This improves mobile support by adding a New Ticket button on the top bar for small viewports. It also fixes the header text being off center.

Add New Ticket button on mobile screens

---

app/controllers/tickets/selected_controller.rb
app/controllers/tickets_controller.rb
app/helpers/application_helper.rb
app/helpers/icon_helper.rb
app/models/concerns/ticket_merge.rb
app/models/merged_ticket.rb
app/models/ticket.rb
app/views/application/_inbox_menu.html.erb
app/views/tickets/_status_dropdown.html.erb
app/views/tickets/index.html.erb
app/views/tickets/show.html.erb
app/views/tickets/update.js.erb
config/locales/de.yml
config/locales/en.yml
test/models/merged_ticket_test.rb

This pull request introduces a feature to merge several tickets into one. This is useful if a client provides additional information in a separate email.
Suppose there are two tickets that actually belong together.
Select those tickets and click "Merge".
All replies of the second ticket and the message of the second ticket itself are copied into new replies that belong to the first ticket.
Only the first ticket remains with status `:open`.
The second ticket's status is changed to `:closed`.
Please let me know what you think of this idea.
I will try this out in production for a couple of days and then post how it went.

New feature: Merge tickets

---

Gemfile
Gemfile.lock
app/controllers/replies_controller.rb
app/mailers/notification_mailer.rb
app/models/concerns/reply_notifications.rb
app/models/reply.rb
app/models/user.rb
app/views/replies/_reply.html.erb
app/views/shared/_notified_users_list.html.erb
app/views/tickets/show.html.erb
config/environments/development.rb
config/locales/de.yml
config/locales/en.yml
test/controllers/replies_controller_test.rb
test/models/reply_test.rb

This pull request solves https://github.com/ivaldi/brimir/issues/259.
While brimir always stores recipients in `reply#notified_users`, it is not always responsible to deliver these notifications. (https://github.com/ivaldi/brimir/commit/3f05af8905dce36fed9b3c39e408cd5fc4ff2846)
Instead, include the other clients in the `To` field when replying to a client to allow the client to send his reply explicitly to other clients or to refrain from doing so. (https://github.com/ivaldi/brimir/commit/fb3025e0e0a53dc5edf1a939e8d8634006bdac48)
**(1) The user may reply via the web ui of brimir.**
- The ticket system suggests recipients based on the former
conversation.
- The user can change the recipients in the web form before
sending the reply.
**(2) The user may reply via email to …

Do not notify other clients silently, when a client replies via email.

---

app/models/mail_message_extension.rb
config/initializers/mail_message_extension.rb

Discussion in https://github.com/ivaldi/brimir/issues/279.
When delivering emails, usually the `To` field is logged. Log files contain a line like "Sent mail to customer@domain.com (49.8ms)". With this pull request, also the `smtp-envelope-to` will be logged: "Sending mail smtp_envelope_to foo@example.com."
I also added the convenience method `Mail::Message#smtp_envelope_to` that reads out the corresponding header field. Usually one would have to use `Mail::Message#header_fields.select { |field| field.name == 'smtp-envelope-to' }`.

Log smtp-envelope-to in `Mail::Message#deliver`.

---

app/mailers/notification_mailer.rb
test/controllers/replies_controller_test.rb

Setting `Mail::Message#smtp_envelope_to=...` directly in addition to passing it to `ActionMailer::Base#mail`.
This fixes https://github.com/ivaldi/brimir/issues/279.
I've just applied this to our production instance. Works fine.
See also:
* https://github.com/ivaldi/brimir/issues/279#issuecomment-233597676
* https://github.com/mikel/mail/issues/1015

Fix multiple-notifications issue #279.

---

app/models/concerns/merged_reply.rb
app/models/reply.rb
test/models/merged_ticket_test.rb

We've experienced some issues with merged tickets: After merging a ticket, we **neither can access the attachments nor the raw message through the merged record**.
This pull request will:
* We already had specs for merging ticket with attachments, but these didn't check whether the attachment and raw message files of the duplicates exist on the file system. Due to the lack of my understanding of [paperclip](https://github.com/thoughtbot/paperclip), I did not realize that duplicating the record would neither duplicate the uploaded file nor link the new record correctly to the old file.
* The fix works retroactively, i.e. when merging the pull request, the fix applies also to tickets merged in the past.
* The fix overrides the `attachments` and `raw_message` methods in a way that also tries …

Attachment and raw message issues for merged tickets

---

app/helpers/avatar_helper.rb

Rails 4.2.7 introduced an XSS fix to the `tag` method (rails/rails@f05af91c68debc0230c302aa9031a253f8786b87) which breaks the Gravatar size (as it's an integer). This changes the size to a string.

Fixes an issue with Gravatar tag breaking

---

app/views/tickets/index.csv.erb

This fixes the Status column in the CSV export (as mentioned in issue #283), based on comments in PR #291

Fix the translation of the status column

---

app/views/tickets/_form.html.erb

Captcha was still showing for logged in users, even though verification was skipped entirely. This pull request should fix this.

Fixed captcha still showing for signed in users

---

CHANGELOG.md
app/controllers/tickets_controller.rb

As mentioned by @mickael-kerjean in issue [#310](https://github.com/ivaldi/brimir/issues/310), ticket creation from the web gui doesn't seem to work for non signed in users when the captcha is disabled.
This request should fix this.

Fixed issue with captcha blocking ticket creation for not signed in users

---

CHANGELOG.md
app/mailers/ticket_mailer.rb
app/views/rules/_form.html.erb
config/locales/en.yml
config/locales/nl.yml
db/migrate/20161122124911_add_to_cc_to_tickets.rb
db/schema.rb
test/models/rule_test.rb

Pulling this request will fix issue [#227](https://github.com/ivaldi/brimir/issues/227) and extends the test suite for the rules model.
Below a .gif showing the behaviour by selecting the new "cc" rule and adding the selected label.
New behaviour is that the _"to"_ filter will now filter on the actual _"to"_ address instead of the verified one, this functionality is added by adding a _"orig_to"_ column to the rules table, for _"cc"_ an additional column is added, _"orig_cc"_.

Allows adding rules to filter on cc and actual to addresses

---

config/initializers/paperclip.rb

Hello,
In our particular institution, we sometimes receive messages from Supportworks which contain an attachment with the 'swm' extension. These cause Brimir to fail as it doesn't recognise the extension. This patch adds a content type mapping to resolves this issue.
Thanks,
James

Added Paperclip initialiser to support Supportworks Mail

---

app/models/attachment.rb
app/models/concerns/email_message.rb

To have `#attached_files` respect the `#attachments` of merged tickets,
redefine `#attached_files` based on `#attachments`.
```ruby
module EmailMessage
def attached_files
attachments.non_inline
end
end
class Attachment
scope :non_inline, -> { where(content_id: nil) }
end
```
Introducing scopes `Attachment.inline` and `Attachment.non_inline`.
Fixes #347.

Define #attached_files based on #attachments. Fixes #347.

---

app/views/tickets/_change_assignee_form.html.erb
app/views/tickets/_form.html.erb

There are a couple of places where the agents appear in select boxes in no particular order. This pull request orders them by email address.

Order Agents by email on 'New ticket' and 'Assign ticket' pages

---

app/views/devise/sessions/new.html.erb
app/views/users/_form.html.erb

The Google+ sign in link was updated as part of the Rails 5 upgrade, but the link format isn't correct now - it appends "google_oauth2" to the link and causes it to fail.
This commit fixes the issue.

Fixing issue with Google+ sign in link

---

app/views/replies/_form.html.erb
app/views/replies/new.js.erb
config/locales/en.yml

We've started using Brimir at https://www.epigenesys.org.uk and have found it great, however we've been double (or triple) checking when we are submitting an internal note that it is not sending a reply. This is a small change to help alleviate that.

send reply button now changes to 'attach note'

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/views/tickets/index.html.erb

As per #359, this replaces the current onfocus/onblur block in the main page with a check based on the Page Visibility API.
The page will only refresh now if the page is hidden and then shown - it should stop the onblur check being intercepted when moving to other pages.

Replace onfocus/onblur with visibility check

---

app/controllers/email_imports_controller.rb
app/mailers/ticket_mailer.rb
app/models/ability.rb
app/views/email_imports/_form.html.erb
app/views/email_imports/new.html.erb
app/views/replies/_reply.html.erb
app/views/tickets/new.html.erb
config/locales/de.yml
config/locales/en.yml
config/routes.rb

Sometimes, people who know the support staff in person, won't write emails to the support email address but to the agents' personal email addresses. We've tried really hard, but we can't get these clients to write to the support email address.
This workaround allows to upload email files (*.eml) from the local mail client and to import them as new tickets.
As uploading multiple files is supported, I guess, this can also be used when migrating to brimir in the first place.
Click on "New ticket", then on "import emails".
After importing several emails from the same thread, it might be useful to [merge them](https://github.com/ivaldi/brimir/pull/242).
- In `TicketMailer#receive`, I'm setting the `created_at` column to the email date …

feature: import eml files as new tickets

---

app/controllers/tickets_controller.rb
app/models/ability.rb
app/models/status_reply.rb
app/views/tickets/_change_subject_form.html.erb
app/views/tickets/show.html.erb
config/locales/de.yml
config/locales/en.yml

Sometimes, clients need a little help naming their tickets. This pull request adds a small button to rename the ticket. Renaming the ticket will create a status reply in the ticket history, but won't send a notification.
We have this in production since today. I'm going to report here in a couple of days if we encounter any issues.

feature: ui to rename ticket

---

app/controllers/tickets/selected_controller.rb

if there is no ticktes selected for merge, then redirect back.

---

README.md

When creating users in the console, password_confirmation is not required.

password_confirmation not needed

---

README.md

Following up on #403, this adds a note to README.md explaining that the preferred JS runtime is Node.js

Add JS runtime information to README

---

app/controllers/replies_controller.rb

This resolves #412 
Earlier changes to some partials led to a 500 error on replies#new due to missing instance vars.  This PR gets those defined and resolves the 500 error.

set missing instance vars - resolves #412

---

config/locales/fr-FR.yml

I've just learned thanks to @thehunt33r that Québec has some pretty weird laws concerning anglicisms which may be why fr-CA translates ticket with "billet".
Right now, fr-FR is just a clone of fr-CA, but since the term "ticket" is way more common in this context, I've fixed the fr-FR locale accordingly. (An alternative term would be "dossier", however, it's more common for old-school businesses such as ex-monopole telco.)
Titles are not capitalized in fr-FR the way this is common in EN, fixed that as well.

Rename "billet" to "ticket" in fr-FR locale

---

app/controllers/replies_controller.rb
test/mailers/notification_mailer_test.rb

A common complaint I'm getting here is that our agents would rather be sent back to the ticket list after replying, rather than going back to the ticket they just updated.
This PR changes the redirect location to send the agent back to the ticket list after they reply to a ticket.

redirect to ticket list after updating ticket

---

.gitignore

A tiny PR excluding `.ruby-version` from Git. As an alternative, `.ruby-version` could also be checked in, but many projects prefer not to.

Ignore .ruby-version and deployment-only files

---

app/assets/javascripts/application.js
app/assets/javascripts/replies.js
app/assets/stylesheets/application.scss
app/controllers/tickets/split_off_controller.rb
app/models/ability.rb
app/models/reply.rb
app/views/replies/_reply.html.erb
config/locales/de.yml
config/locales/en.yml
config/routes.rb

Our clients often reply to an existing ticket, but really want to discuss a separate issue. Therefore, this pull request provides a ui to split off tickets for two common use cases:
In this use case, the client's issue has been resolved and the ticket has been closed. But after a while, the client replies to the ticket and reports a completely separate problem.
Click on "Split off ticket" in order to copy the reply into a new ticket and destroy the reply to the old ticket.
After that, consider [renaming](https://github.com/ivaldi/brimir/pull/372) the new ticket.
In this use case, the client's issue might or might not be resolved, yet. But in a reply, the client comes up with another issue, which is unrelated.
Select the part of the reply, which is unrelated to the current ticket and …

feature: split off tickets

---

CHANGELOG.md
app/assets/javascripts/tickets.js
app/controllers/api/v1/email_templates_controller.rb
app/controllers/tickets_controller.rb
app/models/ability.rb
app/models/email_template.rb
app/views/email_templates/index.html.erb
app/views/replies/_canned_responses.html.erb
app/views/replies/_form.html.erb
config/locales/de.yml
config/locales/en.yml
config/locales/es.yml
config/locales/fr-CA.yml
config/locales/fr-FR.yml
config/routes.rb
test/controllers/api/v1/email_templates_controller_test.rb
test/fixtures/email_templates.yml

"Canned responses" are prepared emails to prevent having to write the same responses to evergreen tickets all the time. This basic implementation simply adds a new `EmailTemplate` kind "canned-response" which can then be selected from the reply form.
---
First of all, you have to create at least one email template of kind "canned response":
To keep things simple, canned responses are not mutually exclusive but always active:
Now, a new dropdown shows up on the reply form:
Choose the canned response of your choice and it prefills the text editor:

Basic implementation of canned responses

---

CHANGELOG.md
app/assets/javascripts/tickets.js
app/controllers/tickets_controller.rb
app/models/email_template.rb
app/views/replies/_canned_replies.html.erb
app/views/replies/_canned_responses.html.erb
app/views/replies/_form.html.erb
config/locales/de.yml
config/locales/en.yml
config/locales/es.yml
config/locales/fr-CA.yml
config/locales/fr-FR.yml
test/controllers/api/v1/email_templates_controller_test.rb
test/fixtures/email_templates.yml

@frenkel Sorry for this followup PR: I've introduced a bug with #435 which has no effect on the application itself, but caused one test to go red. It has slipped my attention. Here's the fix for this and while I'm at it, I've renamed "canned response" to "canned reply" for consistency.

Rename canned response to canned reply

---

app/controllers/settings_controller.rb
app/helpers/application_helper.rb
app/views/layouts/application.html.erb
app/views/settings/edit.html.erb
config/locales/de.yml
config/locales/en.yml
config/locales/fr-CA.yml
config/locales/fr-FR.yml
config/settings.yml
db/migrate/20181011062745_add_javascript_url_to_tenants.rb
db/schema.rb
test/controllers/settings_controller_test.rb

Until now, it was only possible to configure a custom CSS on the tenant.
For some customizing (e.g. renaming submit button text on standalone new ticket view), custom JS is necessary. However, custom JS may open the door to malicious JS injection after getting illegitimate access to any agent's account. Time for some extra security.
There are four new application settings now:
enable_custom_stylesheet (default: true)
Main switch for custom stylesheets.
enable_custom_javascript (default: false)
Main switch for custom javascript.
custom_stylesheet_url (default: nil)
Overrides the URL set on the tenant. This URL will be showed on the settings form as a disabled input.
custom_javascript_url (default: nil)
Overrides the URL set on the tenant. This URLwill be showed on the settings form as a …

Support for custom CSS/JS by app setting or tenant

---

app/controllers/concerns/tickets_strong_params.rb
app/controllers/settings_controller.rb
app/models/concerns/create_from_user.rb
app/views/settings/edit.html.erb
app/views/tickets/_form.html.erb
config/locales/de.yml
config/locales/en.yml
config/locales/fr-CA.yml
config/locales/fr-FR.yml
db/migrate/20181011140158_add_ask_for_name_to_tenants.rb
db/schema.rb
test/controllers/tickets_controller_test.rb

For new tickets created by email and in order to keep the new tickets forms short, setting the user name to what's in front of the email-@ is very nice.
However, for those who heavily rely on new ticket forms and would like to have the real user names, this new tenant setting will come in handy:
Tick the checkbox next to "ask for name on new ticket forms" and users may enter their real name when submitting a new ticket by use of the forms.
---
---

Optionally ask for name on new ticket forms

---

app/views/tickets/_form.html.erb

Very small PR to pass the current `I18n.locale` to the captcha. Instead of the EN default "I'm not a robot", you will get for instance:
(Please ignore the red warning, I made the screenshot off my localhost development.)

Localize captcha

---

app/assets/stylesheets/application.scss
app/controllers/application_controller.rb
app/views/layouts/application.html.erb

Two little commits:
* Fix a bug in RTL handling
* Add controller/action and sign in status classes to the body tag
To explain the latter, here's a copy from the commit message:
>To restyle different parts of the application with a custom stylesheet, it's necessary to have elements to root your custom styles to.
>
>This commit adds the two classes to the body tag:
>* <controller_name>-<action_name> (e.g. "tickets-new")
>* "user-signed-in" if a use has previously authenticated himself
>
>Say, you want to include the public new tickets form into another website by use of an iframe, you can match the styling by rooting your custom styles to "body.tickets-new:not(.user-signed-in)".

RTL and styling roots

---

app/models/concerns/create_from_user.rb

When submitting an invalid new ticket form, no associated user is initialized and therefore the attempt to set "name" kaboomed.
Sorry, this one slipped under my radar.

Fix name= when ticket validation fails
